package by.iposdev.mitsotest.ui.theme

import androidx.compose.ui.graphics.Color

// Primary tones (MITSO Academic Blue)
val PrimaryLight = Color(0xFF005AC1)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFD8E2FF)
val OnPrimaryContainerLight = Color(0xFF001A41)

val PrimaryDark = Color(0xFFADC6FF)
val OnPrimaryDark = Color(0xFF002E69)
val PrimaryContainerDark = Color(0xFF004494)
val OnPrimaryContainerDark = Color(0xFFD8E2FF)

// Secondary tones (Teal / Cyan)
val SecondaryLight = Color(0xFF006874)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFF9EEFFD)
val OnSecondaryContainerLight = Color(0xFF001F24)

val SecondaryDark = Color(0xFF4FD8EB)
val OnSecondaryDark = Color(0xFF00363D)
val SecondaryContainerDark = Color(0xFF004F58)
val OnSecondaryContainerDark = Color(0xFF9EEFFD)

// Tertiary tones (Warm Amber / Coral for expressive highlights)
val TertiaryLight = Color(0xFF7D5700)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFFFDEA8)
val OnTertiaryContainerLight = Color(0xFF271900)

val TertiaryDark = Color(0xFFFFBA38)
val OnTertiaryDark = Color(0xFF422C00)
val TertiaryContainerDark = Color(0xFF5F4100)
val OnTertiaryContainerDark = Color(0xFFFFDEA8)

// Neutral / Surfaces (Light)
val BackgroundLight = Color(0xFFF8F9FF)
val OnBackgroundLight = Color(0xFF191C20)
val SurfaceLight = Color(0xFFF8F9FF)
val OnSurfaceLight = Color(0xFF191C20)
val SurfaceVariantLight = Color(0xFFE0E2EC)
val OnSurfaceVariantLight = Color(0xFF44474E)
val OutlineLight = Color(0xFF74777F)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF2F3FA)
val SurfaceContainerLight = Color(0xFFECEEF4)
val SurfaceContainerHighLight = Color(0xFFE7E8EF)
val SurfaceContainerHighestLight = Color(0xFFE1E2E9)

// Neutral / Surfaces (Dark)
val BackgroundDark = Color(0xFF111318)
val OnBackgroundDark = Color(0xFFE1E2E9)
val SurfaceDark = Color(0xFF111318)
val OnSurfaceDark = Color(0xFFE1E2E9)
val SurfaceVariantDark = Color(0xFF44474E)
val OnSurfaceVariantDark = Color(0xFFC4C6D0)
val OutlineDark = Color(0xFF8E9099)
val SurfaceContainerLowestDark = Color(0xFF0C0E13)
val SurfaceContainerLowDark = Color(0xFF191C20)
val SurfaceContainerDark = Color(0xFF1D2024)
val SurfaceContainerHighDark = Color(0xFF282A2F)
val SurfaceContainerHighestDark = Color(0xFF33353A)

// Expressive Lesson Category Colors
val LectureBadgeBgLight = Color(0xFFE0F2FE)
val LectureBadgeTextLight = Color(0xFF0369A1)
val LectureBadgeBgDark = Color(0xFF0C4A6E)
val LectureBadgeTextDark = Color(0xFFBAE6FD)

val PracticeBadgeBgLight = Color(0xFFFEF3C7)
val PracticeBadgeTextLight = Color(0xFFB45309)
val PracticeBadgeBgDark = Color(0xFF78350F)
val PracticeBadgeTextDark = Color(0xFFFDE68A)

val LabBadgeBgLight = Color(0xFFF3E8FF)
val LabBadgeTextLight = Color(0xFF7E22CE)
val LabBadgeBgDark = Color(0xFF581C87)
val LabBadgeTextDark = Color(0xFFE9D5FF)

val ExamBadgeBgLight = Color(0xFFFFE4E6)
val ExamBadgeTextLight = Color(0xFFBE123C)
val ExamBadgeBgDark = Color(0xFF881337)
val ExamBadgeTextDark = Color(0xFFFECDD3)